// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/telegram/CallsScreen.tsx": () => import("../components/mockups/telegram/CallsScreen.tsx"),
  "./components/mockups/telegram/ChatDetailScreen.tsx": () => import("../components/mockups/telegram/ChatDetailScreen.tsx"),
  "./components/mockups/telegram/ChatsScreen.tsx": () => import("../components/mockups/telegram/ChatsScreen.tsx"),
  "./components/mockups/telegram/ContactsScreen.tsx": () => import("../components/mockups/telegram/ContactsScreen.tsx"),
  "./components/mockups/telegram/SettingsScreen.tsx": () => import("../components/mockups/telegram/SettingsScreen.tsx")
};
